- name: Install apache2
  apt:
    name: [apache2]

- name: Import Certbot PPA
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install Certbot
  apt: 
    name: [certbot,python-certbot-apache]
    
- name: Enable Apache modules
  shell: |
    a2enmod rewrite
    a2enmod ssl

- name: Create default Directory
  file:
    path: /data/config/apache
    state: directory

- name: Create a Apache Log symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /var/log/apache2,dest: /data/logs/apache}
    - {src: /var/log/apache2,dest: /etc/apache2/logs}
    - {src: /etc/apache2/sites-enabled,dest: /data/config/apache/sites-enabled}
    - {src: /etc/apache2/mods-enabled,dest: /data/config/apache/mods-enabled}

- name: Change Directory Owner
  file:
    path: /data/{{item}}
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - wwwroot
    - cert

- name: Configure Apache
  copy:
    src: apache2.conf
    dest: /etc/apache2/

- name: set soft link apache for apache2
  shell: |
    ln -sb /lib/systemd/system/apache2.service  /lib/systemd/system/apache.service
    
- name: Start Apache
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Check Apache Version
  shell: sudo sh -c 'echo "httpd  $(apache2 -v | sed -n 1p)" 1>> /data/logs/install_version.txt'
