#1 Install and configure Apache
- name: Install Apache and 3th modules
  apt:
    name: [apache2,libapache2-mod-xsendfile]
    
- name: Enable Apache modules
  shell: |
    a2enmod rewrite
    a2enmod ssl

- name: Create default Directory
  file:
    path: /data/config/apache
    state: directory

- name: Create a Apache Log symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /etc/apache2,dest: /etc/httpd}
    - {src: /usr/sbin/apache2,dest: /usr/sbin/apache}
    - {src: /usr/sbin/apache2,dest: /usr/sbin/httpd}
    - {src: /etc/apache2/sites-enabled,dest: /etc/httpd/conf.d}
    - {src: /etc/apache2,dest: /etc/httpd/conf}
    - {src: /etc/apache2/apache2.conf,dest: /etc/httpd/conf/httpd.conf}
    - {src: /etc/apache2/sites-available/000-default.conf,dest: /etc/apache2/sites-enabled/vhost.conf}
    - {src: /var/log/apache2,dest: /var/log/httpd}
    - {src: /var/log/apache2,dest: /data/logs/apache}
    - {src: /var/log/apache2,dest: /etc/apache2/logs}
    - {src: /etc/apache2/sites-enabled,dest: /data/config/apache/sites-enabled}
    - {src: /etc/apache2/mods-enabled,dest: /data/config/apache/mods-enabled}

- name: Change Directory Owner
  file:
    path: /data/{{item}}
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - wwwroot
    - cert

- name: Configure Apache
  copy:
    src: apache2.conf
    dest: /etc/apache2/

- name: set soft link apache for apache2
  shell: |
    ln -sb /lib/systemd/system/apache2.service  /lib/systemd/system/apache.service
    
- name: Start Apache
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Check Apache Version
  shell: sudo sh -c 'echo "httpd  $(apache2 -v | sed -n 1p)" 1>> /data/logs/install_version.txt'
  
#2 Install Certbot for Apache
- name: Install certbot
  shell: |
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository universe
    echo "" | add-apt-repository ppa:certbot/certbot 
    apt-get update
    apt-get install -y certbot python3-certbot-nginx
    certbot renew --dry-run
  when: apache_certbot
