# install Apache by OS_family
- name: install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
# install Certbot for apache
- name: Install certbot
  shell: |
    snap install --classic certbot
    ln -sf /snap/bin/certbot /usr/bin/certbot
  when: apache_certbot  
  
# check service state
- name: Check Apache Service
  shell: systemctl status apache | grep Active*
  register: check_apache_service
  notify: check_apache_service
