# install Apache by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
# check service state
- name: Check Apache Service
  shell: systemctl status apache | grep Active*
  register: check_apache_service
  notify: check_apache_service
