# install Apache by OS_family
- name: install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
# install Certbot for apache
- name: Install certbot
  shell: |
    snap install --classic certbot
    ln -sf /snap/bin/certbot /usr/bin/certbot
  when: apache_certbot  

- name: create apache extra Directory
  file:
    path: "{{item}}"
    state: directory
    recurse: true
  loop:
    - /etc/httpd/extra
    
- name: enable extra/*conf
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: "IncludeOptional conf.d/*.conf"
    block: |
      IncludeOptional extra/*.conf;
      
# check service state
- name: Check Apache Service
  shell: systemctl status apache | grep Active*
  register: check_apache_service
  notify: check_apache_service
